const actionTypes = {
  LOAD_QUESTION: 'LOAD_QUESTION',
  LOAD_QUESTION_ERROR: 'LOAD_QUESTION_ERROR',
  FILTER_BY_TAG: 'FILTER_BY_TAG',
  FILTER_BY_TAG_ERROR: 'FILTER_BY_TAG_ERROR',
  FILTER_BY_NO_ANSWER: 'FILTER_BY_NO_ANSWER',
  RESET: 'RESET',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT',
  ADD_USER: 'ADD_USER',
  ADD_USER_ERROR: 'ADD_USER_ERRROR',
  POST_QUESTION: 'POST_QUESTION',
  POST_QUESTION_ERROR: 'POST_QUESTION_ERROR',
  LOAD_QUESTION_DETAIL: 'LOAD_QUESTION_DETAIL',
  LOAD_QUESTION_DETAIL_ERROR: 'LOAD_QUESTION_DETAIL_ERROR',
  LOAD_ANSWER: 'LOAD_ANSWER',
  LOAD_ANSWER_ANSWER: 'LOAD_ANSWER_ANSWER',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  SAVE_USER: 'SAVE_USER',

};

export default actionTypes;
