const actionTypes = {
  LOAD_QUESTION: 'LOAD_QUESTION',
  LOAD_QUESTION_ERROR: 'LOAD_QUESTION_ERROR',
  FILTER_BY_TAG: 'FILTER_BY_TAG',
  FILTER_BY_TAG_ERROR: 'FILTER_BY_TAG_ERROR',
  RESET: 'RESET',

};

export default actionTypes;
